package pers.caijx.leetcode;

/**
 Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.

 Example:

 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e

 Explanation:
 'e' is the letter that was added.
 * Created by Administrator on 2018/4/8/008.
 */
public class FindTheDifference {

    /**
     利用异或的性质，相同位返回0，这样相同的字符都抵消了，剩下的就是后加的那个字符
     * @param s
     * @param t
     * @return
     */
    public char findTheDifference(String s, String t) {
        char c = 0;
        for (int i = 0; i < s.length(); i++) {
            c ^= s.charAt(i);
        }
        for (int i = 0; i < t.length(); i++) {
            c ^= t.charAt(i);
        }
        return c;
    }
}
